name: DonorUI
main: DonorUI\Main
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 0.0.1
author: BajanVlogs

commands:
 donor:
  description: "This is for donors using CustomUI"
